version: "3.8"
services:
  db:
    image: postgres:15
    container_name: db_app
    ports:
      - 5432
    env_file:
      - ".env-non-dev"

  redis:
    image: redis:7
    container_name: redis_app
    command: --port 5370
    expose:
      - 5370
    depends_on:
      - db


  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: AX_Technology
    ports:
      - "1212:8000"
    depends_on:
      - db


volumes:
  db_data:
    name: db_data
  redis_data:
    name: redis_data
