"""delete admin model

Revision ID: 3e862ca6d4bb
Revises: 17cb00a0d1ae
Create Date: 2023-12-29 11:18:48.012917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '3e862ca6d4bb'
down_revision: Union[str, None] = '17cb00a0d1ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_admin_email', table_name='admin')
    op.drop_index('ix_admin_id', table_name='admin')
    op.drop_index('ix_admin_username', table_name='admin')
    op.drop_table('admin')
    op.add_column('user', sa.Column('is_staff', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('is_superuser', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('is_moderator', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_moderator')
    op.drop_column('user', 'is_superuser')
    op.drop_column('user', 'is_staff')
    op.create_table('admin',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
                    sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=True),
                    sa.Column('is_staff', sa.BOOLEAN(), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='admin_pkey')
                    )
    op.create_index('ix_admin_username', 'admin', ['username'], unique=True)
    op.create_index('ix_admin_id', 'admin', ['id'], unique=False)
    op.create_index('ix_admin_email', 'admin', ['email'], unique=True)
    # ### end Alembic commands ###
