"""member model

Revision ID: 8862362c095f
Revises: 3e862ca6d4bb
Create Date: 2023-12-29 14:42:00.479816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8862362c095f'
down_revision: Union[str, None] = '3e862ca6d4bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('membership_start_date', sa.Date(), nullable=True))
    op.add_column('member', sa.Column('membership_end_date', sa.Date(), nullable=True))
    op.drop_column('member', 'membership_period')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('membership_period', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('member', 'membership_end_date')
    op.drop_column('member', 'membership_start_date')
    # ### end Alembic commands ###
